# Generated by Django 3.2.5 on 2021-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210805_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
