# Generated by Django 3.2.5 on 2021-08-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
